import json
from typing import Optional, Dict, Any

from llm.models import Provider, ProviderType


DEFAULT_PROVIDER_DEFINITIONS = [
    {
        "name": "google",
        "provider_type": ProviderType.GOOGLE,
        "base_url": "https://generativelanguage.googleapis.com/v1beta",
        "enabled": True,
        "priority": 1,
        "timeout_ms": 60000,
        "rate_limit_rpm": 60,
        "rate_limit_tpm": 500000,
        "models": [
            "gemini-2.0-flash",
            "gemini-1.5-pro",
            "gemini-1.5-flash",
            "gemini-2.5-flash",
            "gemini-2.5-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "google"},
    },
    {
        "name": "groq",
        "provider_type": ProviderType.GROQ,
        "base_url": "https://api.groq.com/openai/v1",
        "enabled": True,
        "priority": 2,
        "timeout_ms": 60000,
        "rate_limit_rpm": 60,
        "rate_limit_tpm": 1000000,
        "models": [
            "llama-3.1-70b-versatile",
            "llama-3.1-8b-instant",
            "mixtral-8x7b-32768",
            "gemma2-9b-it",
            "deepseek-r1-distill-llama-70b",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "groq"},
    },
    {
        "name": "cerebras",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.cerebras.ai/v1",
        "enabled": True,
        "priority": 3,
        "timeout_ms": 60000,
        "rate_limit_rpm": 60,
        "rate_limit_tpm": 500000,
        "models": [
            "llama3.1-8b",
            "llama3.3-70b",
            "deepseek-r1-distill-llama-70b",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "cerebras"},
    },
    {
        "name": "mistral",
        "provider_type": ProviderType.MISTRAL,
        "base_url": "https://api.mistral.ai/v1",
        "enabled": True,
        "priority": 4,
        "timeout_ms": 60000,
        "rate_limit_rpm": 60,
        "rate_limit_tpm": 400000,
        "models": [
            "mistral-large-latest",
            "mistral-small-latest",
            "pixtral-large-latest",
            "codestral-latest",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "mistral"},
    },
    {
        "name": "openrouter",
        "provider_type": ProviderType.OPENROUTER,
        "base_url": "https://openrouter.ai/api/v1",
        "enabled": True,
        "priority": 5,
        "timeout_ms": 90000,
        "rate_limit_rpm": 60,
        "rate_limit_tpm": 500000,
        "models": [
            "openai/gpt-oss-120b",
            "google/gemini-2.5-flash",
            "anthropic/claude-3.7-sonnet",
            "meta-llama/llama-3.3-70b-instruct",
            "deepseek/deepseek-r1",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "openrouter"},
    },
    {
        "name": "huggingface",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://router.huggingface.co/v1",
        "enabled": True,
        "priority": 6,
        "timeout_ms": 90000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 200000,
        "models": [
            "meta-llama/Llama-3.3-70B-Instruct",
            "Qwen/Qwen3-32B",
            "mistralai/Mistral-Small-24B-Instruct-2501",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "huggingface"},
    },
    {
        "name": "nvidia",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://integrate.api.nvidia.com/v1",
        "enabled": True,
        "priority": 7,
        "timeout_ms": 180000,
        "rate_limit_rpm": 60,
        "rate_limit_tpm": 400000,
        "models": [
            "meta/llama-3.1-70b-instruct",
            "mistralai/mixtral-8x7b-instruct-v0.1",
            "deepseek-ai/deepseek-r1",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "nvidia"},
    },
    {
        "name": "cohere",
        "provider_type": ProviderType.COHERE,
        "base_url": "https://api.cohere.com/v1",
        "enabled": True,
        "priority": 8,
        "timeout_ms": 60000,
        "rate_limit_rpm": 60,
        "rate_limit_tpm": 300000,
        "models": [
            "command-r-plus",
            "command-r",
            "command-r7b-12-2024",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "cohere"},
    },
    {
        "name": "cloudflare",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.cloudflare.com/client/v4/accounts/{ACCOUNT_ID}/ai/run",
        "enabled": True,
        "priority": 9,
        "timeout_ms": 120000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 200000,
        "models": [
            "@cf/meta/llama-3.1-8b-instruct",
            "@cf/mistral/mistral-7b-instruct-v0.2",
            "@cf/qwen/qwen2.5-coder-7b-instruct",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "cloudflare"},
    },
    {
        "name": "zhipu",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://open.bigmodel.cn/api/paas/v4",
        "enabled": True,
        "priority": 10,
        "timeout_ms": 60000,
        "rate_limit_rpm": 60,
        "rate_limit_tpm": 300000,
        "models": [
            "glm-4.5-flash",
            "glm-4.5",
            "glm-4.6",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "zhipu"},
    },
    {
        "name": "ollama",
        "provider_type": ProviderType.OLLAMA,
        "base_url": "https://ollama.com/v1",
        "enabled": True,
        "priority": 11,
        "timeout_ms": 120000,
        "rate_limit_rpm": 20,
        "rate_limit_tpm": 200000,
        "models": [
            "llama3.1",
            "qwen3",
            "deepseek-r1",
            "gemma3",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "ollama"},
    },
    {
        "name": "github",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://models.github.ai/inference",
        "enabled": True,
        "priority": 12,
        "timeout_ms": 60000,
        "rate_limit_rpm": 60,
        "rate_limit_tpm": 300000,
        "models": [
            "openai/gpt-4.1-mini",
            "openai/gpt-4.1",
            "meta/llama-3.1-70b-instruct",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "github"},
    },
    {
        "name": "sail",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.sailresearch.com/v1",
        "enabled": True,
        "priority": 13,
        "timeout_ms": 600000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 300000,
        "models": [
            "sail-advanced",
            "sail-fast",
            "sail-reasoning",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "sail"},
    },
    {
        "name": "llmtr",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://llmtr.com/v1",
        "enabled": True,
        "priority": 14,
        "timeout_ms": 60000,
        "rate_limit_rpm": 60,
        "rate_limit_tpm": 250000,
        "models": [
            "llmtr-fast",
            "llmtr-reasoning",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "llmtr"},
    },
    {
        "name": "gizmo",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.gizmo.ai/v1",
        "enabled": True,
        "priority": 15,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 200000,
        "models": [
            "gizmo-mini",
            "gizmo-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "gizmo"},
    },
    {
        "name": "blockrun",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.blockrun.com/v1",
        "enabled": True,
        "priority": 16,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 200000,
        "models": [
            "blockrun-fast",
            "blockrun-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "blockrun"},
    },
    {
        "name": "moondream",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.moondream.ai/v1",
        "enabled": True,
        "priority": 17,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 200000,
        "models": [
            "moondream-vision",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "moondream"},
    },
    {
        "name": "electronhub",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.electronhub.ai/v1",
        "enabled": True,
        "priority": 18,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 150000,
        "models": [
            "electronhub-mini",
            "electronhub-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "electronhub"},
    },
    {
        "name": "experiential",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.experiential.ai/v1",
        "enabled": True,
        "priority": 19,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 150000,
        "models": [
            "experiential-fast",
            "experiential-reasoning",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "experiential"},
    },
    {
        "name": "router9",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://router9.ai/v1",
        "enabled": True,
        "priority": 20,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 150000,
        "models": [
            "router9-free",
            "router9-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "router9"},
    },
    {
        "name": "septor",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.septor.ai/v1",
        "enabled": True,
        "priority": 21,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 150000,
        "models": [
            "septor-flash",
            "septor-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "septor"},
    },
    {
        "name": "clod",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.clod.io/v1",
        "enabled": True,
        "priority": 22,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 150000,
        "models": [
            "clod-mini",
            "clod-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "clod"},
    },
    {
        "name": "speechify",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.speechify.com/v1",
        "enabled": True,
        "priority": 23,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 150000,
        "models": [
            "speechify-tts",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "speechify"},
    },
    {
        "name": "blaze",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.blaze.ai/v1",
        "enabled": True,
        "priority": 24,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 150000,
        "models": [
            "blaze-fast",
            "blaze-reasoning",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "blaze"},
    },
    {
        "name": "lucidity",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.lucidity.ai/v1",
        "enabled": True,
        "priority": 25,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 150000,
        "models": [
            "lucidity-fast",
            "lucidity-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "lucidity"},
    },
    {
        "name": "airforce",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.airforce.ai/v1",
        "enabled": True,
        "priority": 26,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 150000,
        "models": [
            "airforce-lite",
            "airforce-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "airforce"},
    },
    {
        "name": "dreamprompting",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.dreamprompting.com/v1",
        "enabled": True,
        "priority": 27,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 150000,
        "models": [
            "dream-prompting-fast",
            "dream-prompting-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "dreamprompting"},
    },
    {
        "name": "waterfall",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.waterfall.ai/v1",
        "enabled": True,
        "priority": 28,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 150000,
        "models": [
            "waterfall-fast",
            "waterfall-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "waterfall"},
    },
    {
        "name": "logfare",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.logfare.ai/v1",
        "enabled": True,
        "priority": 29,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 150000,
        "models": [
            "logfare-mini",
            "logfare-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "logfare"},
    },
    {
        "name": "bai",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.b.ai/v1",
        "enabled": True,
        "priority": 30,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 150000,
        "models": [
            "bai-fast",
            "bai-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "bai"},
    },
    {
        "name": "anyapi",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.anyapi.ai/v1",
        "enabled": True,
        "priority": 31,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 200000,
        "models": [
            "anyapi-fast",
            "anyapi-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "anyapi"},
    },
    {
        "name": "radeon",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://developer.amd.com.cn/radeon/api/v1",
        "enabled": True,
        "priority": 32,
        "timeout_ms": 600000,
        "rate_limit_rpm": 15,
        "rate_limit_tpm": 100000,
        "models": [
            "radeon-fast",
            "radeon-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "radeon"},
    },
    {
        "name": "qianfan",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://qianfan.baidubce.com/v2",
        "enabled": True,
        "priority": 33,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 150000,
        "models": [
            "ERNIE-Speed-8K",
            "ERNIE-Lite-8K",
            "ERNIE-Tiny-8K",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "qianfan"},
    },
    {
        "name": "volcengine",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://ark.cn-beijing.volces.com/api/v3",
        "enabled": True,
        "priority": 34,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 200000,
        "models": [
            "doubao-lite-32k",
            "doubao-pro-32k",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "volcengine"},
    },
    {
        "name": "longcat",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.longcat.chat/openai/v1",
        "enabled": True,
        "priority": 35,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 200000,
        "models": [
            "longcat-lite",
            "longcat-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "longcat"},
    },
    {
        "name": "xfyun",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://spark-api-open.xf-yun.com/v1",
        "enabled": True,
        "priority": 36,
        "timeout_ms": 60000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 150000,
        "models": [
            "spark-lite",
            "spark-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "xfyun"},
    },
    {
        "name": "kilo",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.kilo.ai/api/gateway/v1",
        "enabled": True,
        "priority": 37,
        "timeout_ms": 90000,
        "rate_limit_rpm": 30,
        "rate_limit_tpm": 150000,
        "models": [
            "kilo-free",
            "kilo-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "kilo"},
    },
    {
        "name": "pollinations",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://gen.pollinations.ai/v1",
        "enabled": True,
        "priority": 38,
        "timeout_ms": 90000,
        "rate_limit_rpm": 15,
        "rate_limit_tpm": 100000,
        "models": [
            "pollinations-fast",
            "pollinations-reasoning",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "pollinations"},
    },
    {
        "name": "llm7",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.llm7.io/v1",
        "enabled": True,
        "priority": 39,
        "timeout_ms": 60000,
        "rate_limit_rpm": 20,
        "rate_limit_tpm": 100000,
        "models": [
            "llm7-fast",
            "llm7-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "llm7"},
    },
    {
        "name": "opencode",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://opencode.ai/zen/v1",
        "enabled": True,
        "priority": 40,
        "timeout_ms": 60000,
        "rate_limit_rpm": 20,
        "rate_limit_tpm": 150000,
        "models": [
            "opencode-free",
            "opencode-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "opencode"},
    },
    {
        "name": "ovh",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1",
        "enabled": True,
        "priority": 41,
        "timeout_ms": 90000,
        "rate_limit_rpm": 15,
        "rate_limit_tpm": 120000,
        "models": [
            "ovh-fast",
            "ovh-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "ovh"},
    },
    {
        "name": "agnes",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://apihub.agnes-ai.com/v1",
        "enabled": True,
        "priority": 42,
        "timeout_ms": 60000,
        "rate_limit_rpm": 20,
        "rate_limit_tpm": 150000,
        "models": [
            "agnes-flash",
            "agnes-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "agnes"},
    },
    {
        "name": "reka",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.reka.ai/v1",
        "enabled": True,
        "priority": 43,
        "timeout_ms": 60000,
        "rate_limit_rpm": 20,
        "rate_limit_tpm": 150000,
        "models": [
            "reka-flash-3",
            "reka-edge-2603",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "reka"},
    },
    {
        "name": "siliconflow",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.siliconflow.com/v1",
        "enabled": True,
        "priority": 44,
        "timeout_ms": 60000,
        "rate_limit_rpm": 20,
        "rate_limit_tpm": 150000,
        "models": [
            "siliconflow-flux",
            "siliconflow-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "siliconflow"},
    },
    {
        "name": "routeway",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.routeway.ai/v1",
        "enabled": True,
        "priority": 45,
        "timeout_ms": 60000,
        "rate_limit_rpm": 20,
        "rate_limit_tpm": 150000,
        "models": [
            "routeway-free",
            "routeway-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "routeway"},
    },
    {
        "name": "bazaarlink",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://bazaarlink.ai/api/v1",
        "enabled": True,
        "priority": 46,
        "timeout_ms": 60000,
        "rate_limit_rpm": 20,
        "rate_limit_tpm": 150000,
        "models": [
            "bazaarlink-auto-free",
            "bazaarlink-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "bazaarlink"},
    },
    {
        "name": "ainative",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.ainative.studio/api/v1",
        "enabled": True,
        "priority": 47,
        "timeout_ms": 60000,
        "rate_limit_rpm": 20,
        "rate_limit_tpm": 150000,
        "models": [
            "ainative-fast",
            "ainative-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "ainative"},
    },
    {
        "name": "aion",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.aionlabs.ai/v1",
        "enabled": True,
        "priority": 48,
        "timeout_ms": 60000,
        "rate_limit_rpm": 20,
        "rate_limit_tpm": 150000,
        "models": [
            "aion-fast",
            "aion-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "aion"},
    },
    {
        "name": "requesty",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://router.requesty.ai/v1",
        "enabled": True,
        "priority": 49,
        "timeout_ms": 60000,
        "rate_limit_rpm": 20,
        "rate_limit_tpm": 150000,
        "models": [
            "requesty-fast",
            "requesty-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "requesty"},
    },
    {
        "name": "navy",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.navy/v1",
        "enabled": True,
        "priority": 50,
        "timeout_ms": 60000,
        "rate_limit_rpm": 20,
        "rate_limit_tpm": 150000,
        "models": [
            "navy-fast",
            "navy-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "navy"},
    },
    {
        "name": "nara",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://router.bynara.id/v1",
        "enabled": True,
        "priority": 51,
        "timeout_ms": 60000,
        "rate_limit_rpm": 20,
        "rate_limit_tpm": 150000,
        "models": [
            "nara-fast",
            "nara-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "nara"},
    },
    {
        "name": "sealion",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.sea-lion.ai/v1",
        "enabled": True,
        "priority": 52,
        "timeout_ms": 60000,
        "rate_limit_rpm": 20,
        "rate_limit_tpm": 150000,
        "models": [
            "sea-lion-lite",
            "sea-lion-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "sealion"},
    },
    {
        "name": "orcarouter",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.orcarouter.ai/v1",
        "enabled": True,
        "priority": 53,
        "timeout_ms": 60000,
        "rate_limit_rpm": 20,
        "rate_limit_tpm": 150000,
        "models": [
            "orca-free",
            "orca-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "orcarouter"},
    },
    {
        "name": "unorouter",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.unorouter.com/v1",
        "enabled": True,
        "priority": 54,
        "timeout_ms": 60000,
        "rate_limit_rpm": 20,
        "rate_limit_tpm": 150000,
        "models": [
            "unorouter-free",
            "unorouter-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "unorouter"},
    },
    {
        "name": "xkiro",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api.xkiro.com/v1",
        "enabled": True,
        "priority": 55,
        "timeout_ms": 60000,
        "rate_limit_rpm": 20,
        "rate_limit_tpm": 150000,
        "models": [
            "xkiro-free",
            "xkiro-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "xkiro"},
    },
    {
        "name": "modelscope",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://api-inference.modelscope.cn/v1",
        "enabled": True,
        "priority": 56,
        "timeout_ms": 90000,
        "rate_limit_rpm": 20,
        "rate_limit_tpm": 150000,
        "models": [
            "qwen3",
            "deepseek-v3",
            "deepseek-r1",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "modelscope"},
    },
    {
        "name": "aihorde",
        "provider_type": ProviderType.OPENAI_COMPATIBLE,
        "base_url": "https://aihorde.net/api",
        "enabled": True,
        "priority": 57,
        "timeout_ms": 120000,
        "rate_limit_rpm": 10,
        "rate_limit_tpm": 100000,
        "models": [
            "horde-fast",
            "horde-pro",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "aihorde"},
    },
    {
        "name": "custom",
        "provider_type": ProviderType.CUSTOM,
        "base_url": "",
        "enabled": True,
        "priority": 999,
        "timeout_ms": 120000,
        "rate_limit_rpm": 5,
        "rate_limit_tpm": 50000,
        "models": [
            "custom-model",
        ],
        "metadata": {"source": "freellmapi", "provider_family": "custom"},
    },
]


class ProviderService:
    """Provider management service."""

    def __init__(self, db):
        """Initialize provider service."""
        self.db = db
        self.providers: Dict[str, Provider] = {}
        self._load_default_providers()

    def _load_default_providers(self) -> None:
        """Load FreeLLMAPI-style default provider configurations."""
        for definition in DEFAULT_PROVIDER_DEFINITIONS:
            provider = Provider(
                name=definition["name"],
                provider_type=definition["provider_type"],
                base_url=definition["base_url"],
                api_key="",
                api_key_header="Authorization",
                api_key_prefix="Bearer",
                enabled=definition.get("enabled", True),
                priority=definition.get("priority", 100),
                timeout_ms=definition.get("timeout_ms", 60000),
                rate_limit_rpm=definition.get("rate_limit_rpm", 60),
                rate_limit_tpm=definition.get("rate_limit_tpm", 100000),
                models=definition.get("models", []),
                metadata=definition.get("metadata", {}),
            )
            self.add_provider(provider)

    def add_provider(self, provider: Provider) -> None:
        """Add or update provider."""
        self.providers[provider.name] = provider

    def get_provider(self, name: str) -> Optional[Provider]:
        """Get provider by name."""
        return self.providers.get(name)

    def get_providers_for_model(self, model_name: str) -> list:
        """Get all providers that support a model."""
        matching = [
            p for p in self.providers.values()
            if p.enabled and p.matches_model(model_name)
        ]
        return sorted(matching, key=lambda p: p.priority)

    def resolve_provider(
        self, model_name: str
    ) -> Optional[Provider]:
        """Resolve best provider for model."""
        candidates = self.get_providers_for_model(model_name)
        if not candidates:
            return None
        return candidates[0]

    def get_all_providers(self) -> list:
        """Get all providers."""
        return sorted(
            self.providers.values(),
            key=lambda p: p.priority,
        )

    def list_providers(self) -> list:
        """List all providers with metadata."""
        return [p.to_dict() for p in self.get_all_providers()]

    def delete_provider(self, name: str) -> bool:
        """Delete provider."""
        if name in self.providers:
            del self.providers[name]
            return True
        return False
